#:schema node_modules/wrangler/config-schema.json
name = "beaver-ai"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"

[vars]
GOOGLE_CLIENT_ID="734784472277-ike4ja77h9t3khpr1hu1qu8h1b5ssmqg.apps.googleusercontent.com"
GITHUB_CLIENT_ID="Iv23liH2R1uPkNlfkObU"
SUPABASE_URL="https://avjfdfudvssfmhdoiqri.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2amZkZnVkdnNzZm1oZG9pcXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzA1MzQsImV4cCI6MjA2NzYwNjUzNH0.VC5L6JSlRGGH5RK-rjU9snO-du3onCFjaVqvacyYLhM"
STRIPE_PUBLISHABLE_KEY="pk_test_51Ru6i23xeSvGURRPuoD9Zaxjozz0onc0NXVHLhVJSPblwbsESi3EQWQ3jMrs5QDTA15Te8KmGccDhb9SPvrlEDUl00rUeV2EtS"
STRIPE_SECRET_KEY="sk_test_51Ru6i23xeSvGURRP3hfA0yYWFU6krcttJNLjo6fOn6RqPJqSp9TR9GswVXIwSMIAXx4PZiZ1MXw2RUIg8uM1EqmN00sf8nH6nT"
STRIPE_WEBHOOK_SECRET="whsec_your_webhook_secret_here"


[[kv_namespaces]]
binding = "USER_LOGIN"
id = "7138352381ae4e78ac7fab39213a172a"

[[kv_namespaces]]
binding = "KV_STORE"
id = "ae336fab0e664753a694538bd82f6302"
