export const figmaNodeData = {
  name: 'Guwave Data Visualization',
  lastModified: '2025-05-07T03:33:40Z',
  thumbnailUrl:
    'https://s3-alpha.figma.com/thumbnails/a8c2c992-2a19-43bc-b8f0-c2addeb6caa3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ4GOSFWC2T2NV3B2%2F20250508%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20250508T000000Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8898ef6a51f58141e59ee21eac92d80d63e27a9eeb07b7029c04a1cf3d6c8af3',
  version: '2215244694736174671',
  role: 'viewer',
  editorType: 'figma',
  linkAccess: 'view',
  nodes: {
    '3334:112642': {
      document: {
        id: '3334:112642',
        name: 'Frame 626070',
        type: 'FRAME',
        scrollBehavior: 'SCROLLS',
        children: [
          {
            id: '3334:112643',
            name: 'Frame 3594',
            type: 'FRAME',
            scrollBehavior: 'SCROLLS',
            children: [
              {
                id: '3334:112644',
                name: 'Frame 3593',
                type: 'FRAME',
                scrollBehavior: 'SCROLLS',
                children: [
                  {
                    id: '3334:112645',
                    name: '1',
                    type: 'TEXT',
                    scrollBehavior: 'SCROLLS',
                    blendMode: 'PASS_THROUGH',
                    fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1.0, g: 1.0, b: 1.0, a: 1.0 } }],
                    strokes: [],
                    strokeWeight: 1.0,
                    strokeAlign: 'OUTSIDE',
                    styles: { fill: '1:378', text: '1:375' },
                    absoluteBoundingBox: { x: 17315.0, y: 11345.0, width: 24.0, height: 20.0 },
                    absoluteRenderBounds: {
                      x: 17323.97265625,
                      y: 11350.1787109375,
                      width: 4.6484375,
                      height: 10.8212890625,
                    },
                    constraints: { vertical: 'TOP', horizontal: 'LEFT' },
                    layoutAlign: 'STRETCH',
                    layoutGrow: 0.0,
                    layoutSizingHorizontal: 'FILL',
                    layoutSizingVertical: 'HUG',
                    characters: '1',
                    characterStyleOverrides: [],
                    styleOverrideTable: {},
                    lineTypes: ['NONE'],
                    lineIndentations: [0],
                    style: {
                      fontFamily: 'Microsoft YaHei',
                      fontPostScriptName: 'MicrosoftYaHei-Bold',
                      fontStyle: 'Bold',
                      fontWeight: 700,
                      textAutoResize: 'HEIGHT',
                      fontSize: 14.0,
                      textAlignHorizontal: 'CENTER',
                      textAlignVertical: 'TOP',
                      letterSpacing: 0.0,
                      lineHeightPx: 20.0,
                      lineHeightPercent: 108.23951721191406,
                      lineHeightPercentFontSize: 142.85714721679688,
                      lineHeightUnit: 'PIXELS',
                    },
                    layoutVersion: 4,
                    effects: [],
                    interactions: [],
                  },
                ],
                blendMode: 'PASS_THROUGH',
                clipsContent: false,
                background: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: { r: 0.89019608497619629, g: 0.28235295414924622, b: 0.65882354974746704, a: 1.0 },
                  },
                ],
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: { r: 0.89019608497619629, g: 0.28235295414924622, b: 0.65882354974746704, a: 1.0 },
                  },
                ],
                strokes: [],
                cornerRadius: 12.0,
                cornerSmoothing: 0.0,
                strokeWeight: 1.0,
                strokeAlign: 'INSIDE',
                backgroundColor: { r: 0.89019608497619629, g: 0.28235295414924622, b: 0.65882354974746704, a: 1.0 },
                styles: { fills: '2150:182170', fill: '2150:182170' },
                layoutMode: 'VERTICAL',
                counterAxisSizingMode: 'FIXED',
                itemSpacing: 4.0,
                primaryAxisSizingMode: 'FIXED',
                counterAxisAlignItems: 'CENTER',
                primaryAxisAlignItems: 'CENTER',
                layoutWrap: 'NO_WRAP',
                absoluteBoundingBox: { x: 17315.0, y: 11343.0, width: 24.0, height: 24.0 },
                absoluteRenderBounds: { x: 17315.0, y: 11343.0, width: 24.0, height: 24.0 },
                constraints: { vertical: 'TOP', horizontal: 'LEFT' },
                layoutAlign: 'INHERIT',
                layoutGrow: 0.0,
                layoutSizingHorizontal: 'FIXED',
                layoutSizingVertical: 'FIXED',
                effects: [],
                interactions: [],
              },
            ],
            blendMode: 'PASS_THROUGH',
            clipsContent: false,
            background: [],
            fills: [],
            strokes: [],
            strokeWeight: 1.0,
            strokeAlign: 'INSIDE',
            backgroundColor: { r: 0.0, g: 0.0, b: 0.0, a: 0.0 },
            layoutMode: 'HORIZONTAL',
            itemSpacing: 8.0,
            counterAxisAlignItems: 'CENTER',
            layoutWrap: 'NO_WRAP',
            absoluteBoundingBox: { x: 17315.0, y: 11343.0, width: 24.0, height: 24.0 },
            absoluteRenderBounds: { x: 17315.0, y: 11343.0, width: 24.0, height: 24.0 },
            constraints: { vertical: 'TOP', horizontal: 'LEFT' },
            layoutAlign: 'INHERIT',
            layoutGrow: 0.0,
            layoutSizingHorizontal: 'HUG',
            layoutSizingVertical: 'HUG',
            effects: [],
            interactions: [],
          },
          {
            id: '3334:112646',
            name: 'Title、Operation',
            type: 'TEXT',
            scrollBehavior: 'SCROLLS',
            blendMode: 'PASS_THROUGH',
            fills: [
              {
                blendMode: 'NORMAL',
                type: 'SOLID',
                color: { r: 0.090196080505847931, g: 0.090196080505847931, b: 0.090196080505847931, a: 1.0 },
              },
            ],
            strokes: [],
            strokeWeight: 1.0,
            strokeAlign: 'OUTSIDE',
            styles: { fill: '2149:124821', text: '80:51960' },
            absoluteBoundingBox: { x: 17344.0, y: 11343.0, width: 150.0, height: 24.0 },
            absoluteRenderBounds: {
              x: 17344.298828125,
              y: 11347.6123046875,
              width: 147.919921875,
              height: 18.861328125,
            },
            constraints: { vertical: 'TOP', horizontal: 'LEFT' },
            layoutAlign: 'INHERIT',
            layoutGrow: 0.0,
            layoutSizingHorizontal: 'HUG',
            layoutSizingVertical: 'HUG',
            characters: 'Title、Operation',
            characterStyleOverrides: [],
            styleOverrideTable: {},
            lineTypes: ['NONE'],
            lineIndentations: [0],
            style: {
              fontFamily: 'Microsoft YaHei',
              fontPostScriptName: 'MicrosoftYaHei-Bold',
              fontStyle: 'Bold',
              fontWeight: 700,
              textAutoResize: 'WIDTH_AND_HEIGHT',
              fontSize: 18.0,
              textAlignHorizontal: 'LEFT',
              textAlignVertical: 'TOP',
              letterSpacing: 0.0,
              lineHeightPx: 24.0,
              lineHeightPercent: 101.02355194091797,
              lineHeightPercentFontSize: 133.33332824707031,
              lineHeightUnit: 'PIXELS',
            },
            layoutVersion: 4,
            effects: [],
            interactions: [],
          },
          {
            id: '3334:112647',
            name: 'Switch',
            visible: false,
            type: 'INSTANCE',
            scrollBehavior: 'SCROLLS',
            componentId: '1:409',
            componentProperties: {
              打开情况: { value: 'On', type: 'VARIANT', boundVariables: {} },
              状态: { value: 'Default', type: 'VARIANT', boundVariables: {} },
              size: { value: 'small', type: 'VARIANT', boundVariables: {} },
            },
            overrides: [],
            children: [
              {
                id: 'I3334:112647;18:550',
                name: '矩形备份 113',
                type: 'RECTANGLE',
                scrollBehavior: 'SCROLLS',
                blendMode: 'PASS_THROUGH',
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: { r: 0.364705890417099, g: 0.17647059261798859, b: 0.80392158031463623, a: 1.0 },
                  },
                ],
                strokes: [],
                strokeWeight: 0.0,
                strokeAlign: 'CENTER',
                styles: { fill: '1:396' },
                cornerRadius: 12.0,
                cornerSmoothing: 0.0,
                absoluteBoundingBox: { x: 17441.0, y: 11349.0, width: 24.0, height: 12.0 },
                absoluteRenderBounds: null,
                constraints: { vertical: 'TOP', horizontal: 'LEFT' },
                effects: [],
                interactions: [],
              },
              {
                id: 'I3334:112647;18:551',
                name: '椭圆形备份 4',
                type: 'ELLIPSE',
                scrollBehavior: 'SCROLLS',
                blendMode: 'PASS_THROUGH',
                fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1.0, g: 1.0, b: 1.0, a: 1.0 } }],
                strokes: [],
                strokeWeight: 1.0,
                strokeAlign: 'INSIDE',
                styles: { fill: '1:378' },
                absoluteBoundingBox: { x: 17455.0, y: 11351.0, width: 8.0, height: 8.0 },
                absoluteRenderBounds: null,
                constraints: { vertical: 'TOP', horizontal: 'LEFT' },
                effects: [],
                arcData: { startingAngle: 0.0, endingAngle: 6.2831854820251465, innerRadius: 0.0 },
                interactions: [],
              },
            ],
            blendMode: 'PASS_THROUGH',
            clipsContent: false,
            background: [],
            fills: [],
            strokes: [],
            strokeWeight: 1.0,
            strokeAlign: 'INSIDE',
            backgroundColor: { r: 0.0, g: 0.0, b: 0.0, a: 0.0 },
            absoluteBoundingBox: { x: 17441.0, y: 11349.0, width: 24.0, height: 12.0 },
            absoluteRenderBounds: null,
            constraints: { vertical: 'TOP', horizontal: 'LEFT' },
            layoutAlign: 'INHERIT',
            layoutGrow: 0.0,
            layoutSizingHorizontal: 'FIXED',
            layoutSizingVertical: 'FIXED',
            effects: [],
            interactions: [],
          },
          {
            id: '3334:112648',
            name: 'Switch',
            visible: false,
            type: 'INSTANCE',
            scrollBehavior: 'SCROLLS',
            componentId: '1:409',
            componentProperties: {
              打开情况: { value: 'On', type: 'VARIANT', boundVariables: {} },
              状态: { value: 'Default', type: 'VARIANT', boundVariables: {} },
              size: { value: 'small', type: 'VARIANT', boundVariables: {} },
            },
            overrides: [],
            children: [
              {
                id: 'I3334:112648;18:550',
                name: '矩形备份 113',
                type: 'RECTANGLE',
                scrollBehavior: 'SCROLLS',
                blendMode: 'PASS_THROUGH',
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: { r: 0.364705890417099, g: 0.17647059261798859, b: 0.80392158031463623, a: 1.0 },
                  },
                ],
                strokes: [],
                strokeWeight: 0.0,
                strokeAlign: 'CENTER',
                styles: { fill: '1:396' },
                cornerRadius: 12.0,
                cornerSmoothing: 0.0,
                absoluteBoundingBox: { x: 17425.0, y: 11349.0, width: 24.0, height: 12.0 },
                absoluteRenderBounds: null,
                constraints: { vertical: 'TOP', horizontal: 'LEFT' },
                effects: [],
                interactions: [],
              },
              {
                id: 'I3334:112648;18:551',
                name: '椭圆形备份 4',
                type: 'ELLIPSE',
                scrollBehavior: 'SCROLLS',
                blendMode: 'PASS_THROUGH',
                fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1.0, g: 1.0, b: 1.0, a: 1.0 } }],
                strokes: [],
                strokeWeight: 1.0,
                strokeAlign: 'INSIDE',
                styles: { fill: '1:378' },
                absoluteBoundingBox: { x: 17439.0, y: 11351.0, width: 8.0, height: 8.0 },
                absoluteRenderBounds: null,
                constraints: { vertical: 'TOP', horizontal: 'LEFT' },
                effects: [],
                arcData: { startingAngle: 0.0, endingAngle: 6.2831854820251465, innerRadius: 0.0 },
                interactions: [],
              },
            ],
            blendMode: 'PASS_THROUGH',
            clipsContent: false,
            background: [],
            fills: [],
            strokes: [],
            strokeWeight: 1.0,
            strokeAlign: 'INSIDE',
            backgroundColor: { r: 0.0, g: 0.0, b: 0.0, a: 0.0 },
            absoluteBoundingBox: { x: 17425.0, y: 11349.0, width: 24.0, height: 12.0 },
            absoluteRenderBounds: null,
            constraints: { vertical: 'TOP', horizontal: 'LEFT' },
            layoutAlign: 'INHERIT',
            layoutGrow: 0.0,
            layoutSizingHorizontal: 'FIXED',
            layoutSizingVertical: 'FIXED',
            effects: [],
            interactions: [],
          },
        ],
        blendMode: 'PASS_THROUGH',
        clipsContent: false,
        background: [],
        fills: [],
        strokes: [],
        strokeWeight: 1.0,
        strokeAlign: 'INSIDE',
        backgroundColor: { r: 0.0, g: 0.0, b: 0.0, a: 0.0 },
        layoutMode: 'HORIZONTAL',
        itemSpacing: 5.0,
        counterAxisAlignItems: 'CENTER',
        layoutWrap: 'NO_WRAP',
        absoluteBoundingBox: { x: 17315.0, y: 11343.0, width: 179.0, height: 24.0 },
        absoluteRenderBounds: { x: 17315.0, y: 11343.0, width: 179.0, height: 24.0 },
        constraints: { vertical: 'TOP', horizontal: 'LEFT' },
        layoutSizingHorizontal: 'HUG',
        layoutSizingVertical: 'HUG',
        effects: [],
        interactions: [],
      },
      components: {
        '1:409': {
          key: 'f295fbf0f7447c9ea51f6ed97cda4738f410ae38',
          name: '打开情况=On, 状态=Default, size=small',
          description: '',
          remote: true,
          componentSetId: '1:399',
          documentationLinks: [],
        },
      },
      componentSets: {
        '1:399': { key: '376680bd7965891d49e21f4527b5e987b73a7b28', name: 'Switch', description: '', remote: true },
      },
      schemaVersion: 0,
      styles: {
        '1:378': {
          key: 'c0382d3917543b138b72db7c181a37cbd439c278',
          name: 'Old/Neutral/white',
          styleType: 'FILL',
          remote: true,
          description: '',
        },
        '1:375': {
          key: '77716f0553c7ce6722823541f891567957e90bf2',
          name: 'Font 14px-bold',
          styleType: 'TEXT',
          remote: true,
          description: '',
        },
        '2150:182170': {
          key: 'ce3daa4c9ef53b6db65db5a12cb93918283558f0',
          name: 'G/Legend/5',
          styleType: 'FILL',
          remote: true,
          description: '',
        },
        '2149:124821': {
          key: 'f3f817c5d02700581431b7e08ee9ffb989cf28cc',
          name: 'G/Gray/900-TextPrimary',
          styleType: 'FILL',
          remote: true,
          description: '主要文字\nTure Gray / Ture Gray 900\n#171717\n17.93:1\n(AAA) Large text\n(AAA) Normal text',
        },
        '80:51960': {
          key: 'a76ccd867b43324dd370d636c1bd46c5f544f149',
          name: 'Font 18px-bold',
          styleType: 'TEXT',
          remote: true,
          description: '',
        },
        '1:396': {
          key: '4d9dc60e3b611a0da6446b70f07350b0d5eb9374',
          name: 'Color Ramp/Primary/600',
          styleType: 'FILL',
          remote: true,
          description: 'Primary2 / Primary2 600\n#5d2dcd\n7.71:1\n(AAA) Large text\n(AAA) Normal text',
        },
      },
    },
  },
};
